import { Check, LoaderCircle } from '../icons'
import type { AnalysisPlan, Evidence, ModelResult } from '../types'
import { label, metric } from '../api'
import { CurveChart } from './charts'
import { Panel } from './ui'

export function PlanView({ plan }: { plan: AnalysisPlan }) {
  return <div className="analysis-plan"><h3>Autonomous Analysis Plan</h3><ol>{plan.steps.map((step, index) => <li key={step.id} className={step.status}><span className="plan-number">{step.status === 'completed' ? <Check size={16} /> : step.status === 'running' ? <LoaderCircle size={16} className="spin" /> : index + 1}</span><div><div className="plan-title"><strong>{step.title}</strong><span>{step.status}</span></div><details><summary>Why this step?</summary><p>{step.reason}</p><small>Expected: {step.expected_outputs.join(' · ')}</small>{step.columns.length > 0 && <small>Columns: {step.columns.join(', ')}</small>}</details></div></li>)}</ol><details className="analytical-detail"><summary>Target candidates and planner reasoning</summary><p>Suitability scores are transparent heuristics, not calibrated probabilities. An uncertain ranking does not force a target.</p>{plan.target_candidates.map(candidate => <div className="candidate-target" key={candidate.name}><strong>{candidate.name} · {candidate.score.toFixed(2)} · {candidate.confidence}</strong><p>{candidate.reasons.join(' ')}</p></div>)}{plan.reasons.map(reason => <p key={reason}>{reason}</p>)}</details></div>
}

export function EvidenceView({ evidence }: { evidence: Evidence }) {
  return <article className="evidence-record"><div className="evidence-heading"><span className="small-tag">{evidence.id}</span><strong>{evidence.title}</strong></div><p>{evidence.method} · {evidence.sample_rows.toLocaleString()} used / {evidence.population_rows.toLocaleString()} dataset rows</p><details className="analytical-detail"><summary>Computed values and provenance</summary><pre>{JSON.stringify(evidence.values, null, 2)}</pre><p>Source: {evidence.provenance} · Status: {evidence.status}</p></details>{evidence.assumptions.length > 0 && <details className="analytical-detail"><summary>Assumptions and limitations</summary>{[...evidence.assumptions, ...evidence.limitations].map(note => <p key={note}>{note}</p>)}</details>}</article>
}

export function ModelReliability({ result }: { result: ModelResult }) {
  return <Panel title="Model reliability and limitations" subtitle="Development stability, held-out probability calibration, and review flags.">
    <div className="reliability-summary"><div><span>CV stability</span><strong>{result.model_stability?.status || 'Not recorded'}</strong><small>{result.cross_validation?.mean !== undefined ? `${result.cross_validation.mean.toFixed(3)} ± ${result.cross_validation.std?.toFixed(3) || '—'}` : result.model_stability?.reason}</small></div><div><span>Probability calibration</span><strong>{result.calibration?.status || 'Not applicable'}</strong>{result.calibration && <small>Brier score: {result.calibration.brier_score.toFixed(4)}</small>}</div><div><span>Baseline context</span><strong>{result.baseline_metrics?.[result.primary_metric] !== undefined ? metric(result.primary_metric, result.baseline_metrics[result.primary_metric]) : 'Not recorded'}</strong><small>{label(result.primary_metric)} · held-out baseline</small></div></div>
    {result.class_imbalance && <details className="analytical-detail" open={result.class_imbalance.severe}><summary>{result.class_imbalance.severe ? 'Severe class imbalance — review minority outcomes' : 'Class distribution and metric policy'}</summary>{result.class_imbalance.distribution.map(item => <p key={item.class}>{item.class}: {item.rows.toLocaleString()} rows ({(item.share * 100).toFixed(2)}%)</p>)}<p>{result.class_imbalance.policy}</p><p>Positive outcome: {result.positive_class || 'Multiclass'}</p></details>}
    {result.leakage?.flags.length ? <div className="inline-error" role="alert"><strong>Potential target leakage — review required</strong>{result.leakage.flags.map(flag => <details className="analytical-detail" key={flag.feature}><summary>{flag.feature}</summary><p>{flag.reasons.join(' ')}</p><p>{flag.action}</p></details>)}</div> : <p className="field-help">No potential leakage flags were recorded by the supported checks; this does not prove all features are available at prediction time.</p>}
    {result.calibration?.reliability.length ? <details className="analytical-detail"><summary>Probability reliability curve</summary><CurveChart data={result.calibration.reliability} xKey="predicted_probability" yKey="observed_frequency" xLabel="Predicted probability" yLabel="Observed frequency" /><p>{result.calibration.note}</p></details> : null}
    {result.threshold_analysis && <details className="analytical-detail"><summary>Validation-only decision threshold tradeoffs</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>Threshold</th><th>Precision</th><th>Recall</th><th>F1</th><th>Balanced accuracy</th></tr></thead><tbody>{result.threshold_analysis.rows.map(row => <tr key={row.threshold}><td>{row.threshold}</td><td>{metric('precision', row.precision)}</td><td>{metric('recall', row.recall)}</td><td>{metric('f1', row.f1)}</td><td>{metric('accuracy', row.balanced_accuracy)}</td></tr>)}</tbody></table></div><p>{result.threshold_analysis.policy}</p></details>}
    <details className="analytical-detail"><summary>Model limitations and stability rule</summary>{[result.model_stability?.rule, ...(result.model_limitations || [])].filter(Boolean).map(note => <p key={note}>{note}</p>)}</details>
    {result.training_warnings?.length ? <details className="analytical-detail"><summary>Recorded training warnings</summary>{result.training_warnings.map(note => <p key={note}>{note}</p>)}</details> : null}
  </Panel>
}
