import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { ArrowLeft, ArrowRight, Download, LoaderCircle, Sparkles } from '../icons'
import { api, download } from '../api'
import type { AnalysisPlan, Run } from '../types'
import { EvidenceView, ModelReliability, PlanView } from '../components/AnalyticalEvidence'
import { TemporalChart } from '../components/charts'
import { ErrorState, Loading, PageHeading, Panel, Status } from '../components/ui'

const tabs = ['Findings', 'Objective & plan', 'Execution', 'Statistics & evidence', 'ML & explainability', 'Recommendations', 'Report']

export default function AnalysisDetail() {
  const { id } = useParams()
  const [tab, setTab] = useState('Findings')
  const [downloading, setDownloading] = useState(false)
  useEffect(() => { setTab('Findings') }, [id])
  const queryClient = useQueryClient()
  const navigate = useNavigate()
  const query = useQuery({ queryKey: ['run', id], queryFn: () => api<Run>(`/analysis-runs/${id}`), refetchInterval: value => ['queued', 'running'].includes(value.state.data?.status || '') ? 1500 : false })
  const rerun = useMutation({ mutationFn: () => api<Run>(`/analysis-runs/${id}/rerun`, { method: 'POST', body: '{}' }), onSuccess: run => { queryClient.invalidateQueries({ queryKey: ['runs'] }); queryClient.invalidateQueries({ queryKey: ['experiments'] }); navigate(`/analysis/${run.id}`); toast.success('Re-run started with stored configuration') }, onError: (error: Error) => toast.error(error.message) })
  const cancel = useMutation({ mutationFn: () => api<Run>(`/analysis-runs/${id}/cancel`, { method: 'POST' }), onSuccess: run => queryClient.setQueryData(['run', id], run), onError: (error: Error) => toast.error(error.message) })
  async function getArtifact(report: boolean) { setDownloading(true); try { await download(`/analysis-runs/${id}/${report ? 'report' : 'download'}`, report ? 'analytiq-analytical-report.html' : 'analytiq-analysis.zip') } catch (error) { toast.error((error as Error).message) } finally { setDownloading(false) } }
  if (query.isLoading) return <Loading text="Loading the analytical investigation…" />
  if (query.error) return <ErrorState error={query.error} retry={() => query.refetch()} />
  const run = query.data!
  const analysis = run.result?.analysis
  const plan = analysis?.plan || run.config.analysis_plan as AnalysisPlan | undefined
  const active = ['queued', 'running'].includes(run.status)
  const evidence = analysis?.evidence || []
  const temporal = evidence.find(item => item.kind === 'temporal' && item.status === 'completed')
  const temporalPoints = (temporal?.values.points || []) as { date: string; value: number | null; rolling_average: number | null }[]
  const forecast = temporal?.values.forecast as { status: string; reason?: string; selected_model?: string; test_metrics?: { mae: number; rmse: number }; horizon?: { date: string; value: number }[]; evaluation?: string; limitation?: string } | undefined
  return <>
    <Link to="/analyses" className="back-link"><ArrowLeft size={16} />Back to analyses</Link>
    <PageHeading eyebrow="OBJECTIVE → PLAN → EVIDENCE → ACTION" title="Your autonomous analysis." text={run.objective} actions={<>{!active && <button className="button secondary" disabled={rerun.isPending} onClick={() => rerun.mutate()}>{rerun.isPending ? <LoaderCircle size={16} className="spin" /> : <Sparkles size={16} />}Re-run analysis</button>}{analysis && <button className="button primary" disabled={downloading} onClick={() => getArtifact(true)}><Download size={16} />Download report</button>}</>} />
    <div className="run-meta"><Status status={run.status} /><span>{analysis ? `${analysis.insights.length} evidence-backed findings` : run.stage}</span>{typeof run.config.experiment_id === 'string' && <Link className="text-link" to="/experiments">View experiment<ArrowRight size={14} /></Link>}</div>
    <div className="analyst-journey" aria-label="Analyst workflow">{['Objective', 'Autonomous plan', 'Selected analyses', 'Evidence & findings', 'Optional model', 'Recommended actions'].map((item, index) => <span key={item}><b>{index + 1}</b>{item}</span>)}</div>
    {active && <Panel title={run.stage} subtitle="You can leave this page; the plan and execution trace are stored."><div className="progress-track large"><i style={{ width: `${run.progress}%` }} /></div><p className="field-help">{run.progress}% complete</p><button className="button secondary" disabled={cancel.isPending} onClick={() => cancel.mutate()}>Cancel analysis</button></Panel>}
    {run.error && <div className="inline-error" role="alert">{run.error}</div>}
    <div className="tabs" aria-label="Analytical views">{tabs.map(title => <button key={title} className={title === tab ? 'active' : ''} aria-pressed={title === tab} onClick={() => setTab(title)}>{title}</button>)}</div>
    {(tab === 'Objective & plan' || !analysis && tab === 'Findings') && <><Panel title="Analytical objective" subtitle="Your question controls which analyses are eligible."><p>{run.objective}</p>{plan && <div className="info-note"><strong>{plan.ml_decision.use_ml ? 'ML selected' : 'ML not required'}</strong><span>{plan.ml_decision.reason}</span></div>}</Panel>{plan && <Panel><PlanView plan={plan} /></Panel>}</>}
    {tab === 'Findings' && analysis && <>
      <section className="analytical-summary"><span className="eyebrow">EXECUTIVE RESULT</span><h2>What the evidence tells us</h2><p>{analysis.executive_summary}</p><div className="summary-methods"><span>{evidence.length} computed evidence records</span><span>{analysis.hypotheses.length} exploratory hypotheses</span><span>{analysis.ml_decision.use_ml ? 'Evaluated ML included' : 'ML explicitly skipped'}</span></div></section>
      <div className="results-help"><Sparkles size={18} /><div><strong>Why this workflow?</strong> {analysis.ml_decision.reason}</div></div>
      {temporalPoints.length > 0 && <Panel title="The temporal story" subtitle={`${temporal?.values.aggregation} per ${temporal?.values.frequency} period; missing periods remain visible.`}><TemporalChart data={temporalPoints} /><p className="field-help">{temporal?.limitations[0]}</p></Panel>}
      {analysis.plan.intent === 'forecast' && forecast && <Panel title="Evaluated forecast" subtitle={forecast.status === 'completed' ? `Selected ${forecast.selected_model}; separate-test MAE ${forecast.test_metrics?.mae.toFixed(3)}.` : forecast.reason}>{forecast.horizon && <><div className="table-scroll"><table className="data-table"><thead><tr><th>Future period</th><th>Baseline forecast</th></tr></thead><tbody>{forecast.horizon.map(point => <tr key={point.date}><td>{point.date.slice(0, 10)}</td><td>{point.value.toFixed(3)}</td></tr>)}</tbody></table></div><p className="field-help">{forecast.evaluation}</p><div className="info-note">{forecast.limitation}</div></>}</Panel>}
      <div className="finding-list">{analysis.insights.map(finding => <article className="finding-card" key={finding.id}><div className="finding-heading"><span className={`confidence-badge ${finding.confidence.toLowerCase()}`}>{finding.confidence}-CONFIDENCE FINDING</span><span className="small-tag">{finding.type.replaceAll('_', ' ')}</span></div><h3>{finding.finding}</h3><p><strong>Why this matters.</strong> {finding.why_it_matters}</p><details className="analytical-detail"><summary>Evidence and confidence reasoning</summary>{finding.confidence_reasons.map(reason => <p key={reason}>{reason}</p>)}{finding.evidence_ids.map(evidenceId => { const item = evidence.find(item => item.id === evidenceId); return item ? <EvidenceView key={evidenceId} evidence={item} /> : null })}{finding.limitations.map(note => <p className="field-help" key={note}>{note}</p>)}</details>{analysis.recommendations.find(item => item.insight_id === finding.id) && <div className="recommended-action"><strong>Recommended next step</strong><p>{analysis.recommendations.find(item => item.insight_id === finding.id)?.action}</p></div>}</article>)}</div>
      <div className="info-note">Confidence is a transparent evidence rule, not a probability. These findings are observational and do not establish causality.</div>
    </>}
    {tab === 'Execution' && <Panel title="Analytical execution trace" subtitle="Each selected step records its reason, result and evidence references."><ol className="analytical-trace">{run.events.map((event, index) => <li key={index}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{event.stage}</strong><p>{event.detail}</p>{event.evidence_ids?.length ? <small>Evidence: {event.evidence_ids.join(', ')}</small> : null}<small>{new Date(event.at).toLocaleString()}</small></div></li>)}</ol></Panel>}
    {tab === 'Statistics & evidence' && analysis && <><Panel title="Exploratory hypothesis testing" subtitle="Tests include effect sizes and Benjamini–Hochberg adjusted p-values; independent replication is required."><div className="table-scroll"><table className="data-table"><thead><tr><th>Hypothesis</th><th>Adjusted p</th><th>Effect size</th><th>Conclusion</th><th>Evidence</th></tr></thead><tbody>{analysis.hypotheses.map(item => <tr key={item.id}><td className="wrapping-cell">{item.hypothesis}</td><td>{item.q_value.toPrecision(3)}</td><td>{item.effect_size.toPrecision(3)}<small className="cell-secondary">{item.effect_measure}</small></td><td className="wrapping-cell">{item.conclusion}</td><td>{item.evidence_id}</td></tr>)}</tbody></table></div></Panel><Panel title="All computed evidence" subtitle="Expand a record for exact values, sample scope, assumptions and provenance.">{evidence.map(item => <EvidenceView key={item.id} evidence={item} />)}</Panel></>}
    {tab === 'ML & explainability' && analysis && <><Panel title="Machine-learning decision" subtitle="Autonomy includes deciding when a model is unnecessary."><p>{analysis.ml_decision.reason}</p>{run.result?.model_name && <Link className="button primary" to={`/runs/${run.id}?studio=1`}>Open model studio & predictions<ArrowRight size={16} /></Link>}</Panel>{run.result?.model_name && <ModelReliability result={run.result} />}{analysis.leakage.flags.length > 0 && <Panel title="Potential leakage review">{analysis.leakage.flags.map(flag => <div className="evidence-record" key={flag.feature}><strong>{flag.feature}</strong><p>{flag.reasons.join(' ')}</p><p>{flag.action}</p></div>)}</Panel>}</>}
    {tab === 'Recommendations' && analysis && <><Panel title="Evidence-backed next steps" subtitle="Suggestions follow computed findings and do not promise causal impact.">{analysis.recommendations.map(item => <article className="recommendation-record" key={item.id}><span className="eyebrow">{item.id} · EVIDENCE {item.evidence_ids.join(', ')}</span><h3>{item.action}</h3><p>{item.rationale}</p><small>{item.limitation}</small></article>)}</Panel><Panel title="Limitations to keep in mind">{analysis.limitations.map(note => <p className="limitation-note" key={note}>{note}</p>)}</Panel></>}
    {tab === 'Report' && analysis && <>{run.result?.llm_explanation && <Panel title="Evidence-focused explanation" subtitle="The optional language model selected relevant precomputed statements; quantities and conclusions remain Python-generated."><p className="report-content">{run.result.llm_explanation}</p></Panel>}<Panel title="Final analytical report" subtitle="Computed sections cover the objective, plan, statistics, ML decision, anomalies, forecast, actions and reproducibility." action={<button className="button secondary" disabled={downloading} onClick={() => getArtifact(false)}><Download size={16} />Download evidence package</button>}>{analysis.report_sections.map(section => <details className="report-section" key={section.title} open={section.title === 'Executive Summary'}><summary>{section.title}</summary><pre>{section.text}</pre></details>)}</Panel><Panel title="Reproducibility contract"><details className="analytical-detail"><summary>Dataset hash, stored configuration, seed and runtime versions</summary><pre>{JSON.stringify(analysis.reproducibility, null, 2)}</pre></details></Panel></>}
  </>
}
