import { expect, test } from '@playwright/test'

test('demo → exploration → training → prediction → export', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.screenshot({ path: testInfo.outputPath('sign-in.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png'), fullPage: true })
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Customer Churn', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'How are the values distributed?' })).toBeVisible()
  await page.getByRole('button', { name: 'Data table', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'CUS-00000' })).toBeVisible()
  await page.getByRole('button', { name: 'Ask a question', exact: true }).click()
  await page.getByRole('button', { name: 'What are the missing values?' }).click()
  await expect(page.getByText(/55 missing/)).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Train a model', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to goal' }).click()
  await page.getByRole('button', { name: 'Review model setup' }).click()
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Model results', exact: true })).toBeVisible({ timeout: 90000 })
  await page.getByRole('button', { name: 'Model comparison', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: 'Selection score' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand the model', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'SHAP: feature contributions' })).toBeVisible()
  await page.getByRole('button', { name: 'Try predictions', exact: true }).click()
  const predicting = page.waitForResponse(response => response.url().includes('/api/models/') && response.url().endsWith('/predict') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Generate prediction' }).click()
  expect((await predicting).status()).toBe(200)
  await expect(page.getByText('PREDICTED OUTCOME')).toBeVisible()
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download model', exact: true }).click()
  const download = await downloading
  expect(download.suggestedFilename()).toBe('analytiq-solution.zip')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark & immersive' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('link', { name: 'Explore API documentation' })).toHaveAttribute('href', '/docs')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'A workspace that feels like you.' })).toBeVisible()
  expect((await page.request.get('/docs')).status()).toBe(200)
  expect((await page.request.get('/api/not-a-real-endpoint')).status()).toBe(404)
})

test('mobile workspace navigation and visualizations', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Retail Sales', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'How are the values distributed?' })).toBeVisible()
  await page.getByRole('heading', { name: 'Compare two numeric columns' }).scrollIntoViewIfNeeded()
  await expect(page.locator('.recharts-scatter-symbol').first()).toBeVisible({ timeout: 15000 })
  await page.screenshot({ path: testInfo.outputPath('explorer-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('clustering wizard → groups → SHAP → group prediction', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Retail Sales', exact: false }).click()
  await page.getByRole('main').getByRole('button', { name: 'Train a model', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to goal' }).click()
  await page.getByRole('radio', { name: /Find groups/ }).check()
  await page.getByRole('button', { name: 'Review model setup' }).click()
  await expect(page.getByText('Discover similar groups', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Model results', exact: true })).toBeVisible({ timeout: 90000 })
  await expect(page.getByRole('heading', { name: 'See the discovered groups' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand the model', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'SHAP: feature contributions' })).toBeVisible()
  await page.getByRole('button', { name: 'Try predictions', exact: true }).click()
  const predicting = page.waitForResponse(response => response.url().includes('/api/models/') && response.url().endsWith('/predict') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Generate prediction' }).click()
  expect((await predicting).status()).toBe(200)
  await expect(page.getByText('PREDICTED OUTCOME')).toBeVisible()
  await expect(page.locator('.prediction-result > strong')).toHaveText(/Group \d+/)
})
