import { expect, test } from '@playwright/test'

test('demo → exploration → training → prediction → export', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.screenshot({ path: testInfo.outputPath('sign-in.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png'), fullPage: true })
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Customer Churn', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'How are the values distributed?' })).toBeVisible()
  await page.getByRole('button', { name: 'Data table', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'CUS-00000' })).toBeVisible()
  await page.getByRole('button', { name: 'Ask a question', exact: true }).click()
  await page.getByRole('button', { name: 'What are the missing values?' }).click()
  await expect(page.getByText(/55 missing/)).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Train a model', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to goal' }).click()
  await page.getByRole('button', { name: 'Review model setup' }).click()
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Model results', exact: true })).toBeVisible({ timeout: 90000 })
  await page.getByRole('button', { name: 'Model comparison', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: 'Selection score' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand the model', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'SHAP: feature contributions' })).toBeVisible()
  await page.getByRole('button', { name: 'Try predictions', exact: true }).click()
  const predicting = page.waitForResponse(response => response.url().includes('/api/models/') && response.url().endsWith('/predict') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Generate prediction' }).click()
  expect((await predicting).status()).toBe(200)
  await expect(page.getByText('PREDICTED OUTCOME')).toBeVisible()
  await page.getByRole('button', { name: 'What-if scenario', exact: true }).click()
  await page.getByLabel('Change input column').selectOption('monthly_charges')
  await page.getByLabel('Scenario value').fill('95')
  const scenario = page.waitForResponse(response => response.url().endsWith('/scenario') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Compare scenario', exact: true }).click()
  expect((await scenario).status()).toBe(200)
  await expect(page.getByText('MODEL-BASED SCENARIO', { exact: true })).toBeVisible()
  await expect(page.getByText(/does not establish causal impact/)).toBeVisible()
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download model', exact: true }).click()
  const download = await downloading
  expect(download.suggestedFilename()).toBe('analytiq-solution.zip')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark & immersive' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('link', { name: 'Explore API documentation' })).toHaveAttribute('href', '/docs')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'A workspace that feels like you.' })).toBeVisible()
  expect((await page.request.get('/docs')).status()).toBe(200)
  expect((await page.request.get('/api/not-a-real-endpoint')).status()).toBe(404)
})

test('mobile workspace navigation and visualizations', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Retail Sales', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'How are the values distributed?' })).toBeVisible()
  await page.getByRole('heading', { name: 'Compare two numeric columns' }).scrollIntoViewIfNeeded()
  await expect(page.locator('.recharts-scatter-symbol').first()).toBeVisible({ timeout: 15000 })
  await page.screenshot({ path: testInfo.outputPath('explorer-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('clustering wizard → groups → SHAP → group prediction', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('link', { name: 'Retail Sales', exact: false }).click()
  await page.getByRole('main').getByRole('button', { name: 'Train a model', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to goal' }).click()
  await page.getByRole('radio', { name: /Find groups/ }).check()
  await page.getByRole('button', { name: 'Review model setup' }).click()
  await expect(page.getByText('Discover similar groups', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Model results', exact: true })).toBeVisible({ timeout: 90000 })
  await expect(page.getByRole('heading', { name: 'See the discovered groups' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand the model', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'SHAP: feature contributions' })).toBeVisible()
  await page.getByRole('button', { name: 'Try predictions', exact: true }).click()
  const predicting = page.waitForResponse(response => response.url().includes('/api/models/') && response.url().endsWith('/predict') && response.request().method() === 'POST', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Generate prediction' }).click()
  expect((await predicting).status()).toBe(200)
  await expect(page.getByText('PREDICTED OUTCOME')).toBeVisible()
  await expect(page.locator('.prediction-result > strong')).toHaveText(/Group \d+/)
})

test('autonomous diagnostic objective → plan → evidence → recommendations → re-run', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('button', { name: 'Try time-series sample', exact: true }).click()
  await page.getByRole('link', { name: 'Monthly Sales', exact: false }).click()
  await page.getByRole('button', { name: 'Data quality', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Data quality center' })).toBeVisible()
  const reviewing = page.waitForResponse(response => response.url().includes('/quality?target=sales'))
  await page.getByLabel('Review target').selectOption('sales')
  expect((await reviewing).status()).toBe(200)
  await page.getByRole('main').getByRole('button', { name: 'Analyze data', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to objective' }).click()
  await page.getByRole('textbox', { name: 'Analytical objective', exact: true }).fill('Why did sales decrease?')
  await page.getByRole('button', { name: 'Preview analysis plan' }).click()
  await expect(page.getByRole('heading', { name: 'Autonomous Analysis Plan' })).toBeVisible()
  await expect(page.getByRole('dialog').locator('.info-note')).toContainText('Machine learning was not used')
  await page.getByRole('button', { name: 'Start autonomous analysis' }).click()
  await expect(page.getByRole('heading', { name: 'What the evidence tells us' })).toBeVisible({ timeout: 90000 })
  await expect(page.getByText('ML explicitly skipped', { exact: true })).toBeVisible()
  const analyticalUrl = page.url()
  const runId = new URL(analyticalUrl).pathname.split('/').pop()
  await page.goto(`/runs/${runId}?studio=1`)
  await expect(page).toHaveURL(analyticalUrl)
  await expect(page.getByRole('heading', { name: 'What the evidence tells us' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('autonomous-findings-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: 'Objective & plan', exact: true }).click()
  const temporal = page.locator('.analysis-plan li').filter({ hasText: 'Trend and temporal analysis' })
  await temporal.getByText('Why this step?', { exact: true }).click()
  await expect(temporal.getByText(/A valid date column/)).toBeVisible()
  await page.getByRole('button', { name: 'Execution', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Analytical execution trace' })).toBeVisible()
  await expect(page.locator('.analytical-trace li').first()).toBeVisible()
  await page.getByRole('button', { name: 'Statistics & evidence', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: 'Adjusted p', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Recommendations', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Evidence-backed next steps' })).toBeVisible()
  await expect(page.locator('.recommendation-record').first()).toBeVisible()
  await page.getByRole('button', { name: 'Report', exact: true }).click()
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download evidence package' }).click()
  expect((await downloading).suggestedFilename()).toBe('analytiq-analysis.zip')
  const originalUrl = page.url()
  await page.getByRole('button', { name: 'Re-run analysis', exact: true }).click()
  await expect.poll(() => page.url()).not.toBe(originalUrl)
  await expect(page.getByRole('heading', { name: 'What the evidence tells us' })).toBeVisible({ timeout: 90000 })
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: /Experiments/ }).click()
  await expect(page.getByRole('link', { name: 'Why did sales decrease?', exact: true })).toHaveCount(2)
})

test('mobile autonomous forecast shows evaluated baselines and no overflow', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Datasets', exact: false }).first().click()
  await page.getByRole('button', { name: 'Try time-series sample', exact: true }).click()
  await page.getByRole('link', { name: 'Monthly Sales', exact: false }).click()
  await page.getByRole('main').getByRole('button', { name: 'Analyze data', exact: true }).click()
  await page.getByRole('button', { name: 'Continue to objective' }).click()
  await page.getByRole('textbox', { name: 'Analytical objective', exact: true }).fill('Forecast future sales for the next month.')
  await page.getByRole('button', { name: 'Preview analysis plan' }).click()
  await expect(page.getByRole('heading', { name: 'Autonomous Analysis Plan' })).toBeVisible()
  await page.getByRole('button', { name: 'Start autonomous analysis' }).click()
  await expect(page.getByRole('heading', { name: 'Evaluated forecast', exact: true })).toBeVisible({ timeout: 90000 })
  await expect(page.getByRole('columnheader', { name: 'Baseline forecast' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('autonomous-forecast-mobile.png'), fullPage: true })
})

test('autonomous prediction chooses ML and opens the preserved model studio', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Try the live demo' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Demo/ })).toBeVisible({ timeout: 20000 })
  await page.getByRole('main').getByRole('button', { name: 'Analyze data', exact: true }).click()
  await page.getByRole('combobox', { name: 'Dataset', exact: true }).selectOption({ label: 'Customer Churn' })
  await page.getByRole('button', { name: 'Continue to objective' }).click()
  await page.getByRole('textbox', { name: 'Analytical objective', exact: true }).fill('Predict customer churn.')
  await page.getByRole('button', { name: 'Preview analysis plan' }).click()
  await expect(page.getByRole('dialog').locator('.info-note')).toContainText('predictive objective and a suitable target')
  await page.getByRole('button', { name: 'Start autonomous analysis' }).click()
  await expect(page.getByRole('heading', { name: 'What the evidence tells us' })).toBeVisible({ timeout: 90000 })
  await page.getByRole('button', { name: 'ML & explainability', exact: true }).click()
  await page.getByRole('link', { name: 'Open model studio & predictions', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Model results', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Model reliability and limitations' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand the model', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'SHAP: feature contributions' })).toBeVisible()
})
